"""
Gemstone Financial — Semantic Layer Demo
=============================================
Streamlit visualization for the four-tier Cortex Analyst variance study.

Loads the most recent run from variance/results/*.json and renders:
  1. Header scorecard  — accuracy across all four tiers at a glance
  2. Summary bar chart — Status breakdown by tier (stacked bar)
  3. Comparison table  — One row per question, expandable per tier
  4. Detail expanders  — Full SQL, result rows, ground truth, failure narrative

Four tiers (any subset may be present in a given results file):
  bronze     — raw Bronze tables (fragmented, no cross-source joins)
  silver     — SILVER.POSITIONS_INTEGRATED (naive, A7–A11 embedded)
  gold_naive — GOLD_NAIVE.POSITIONS_NAIVE (assumption-based, possibly worse)
  gold       — GOLD DW + semantic model (governed, correct answers)

Requires a results file generated by:
  python variance/runner.py

Run with:
  streamlit run app/streamlit_app.py
"""

import json
import subprocess
import sys
from pathlib import Path

import pandas as pd
import plotly.graph_objects as go
import streamlit as st

sys.path.insert(0, str(Path(__file__).parent.parent))
from variance.comparator import score
from variance.ground_truth import compute_all
from variance.questions import QUESTIONS

_PROJECT_ROOT = Path(__file__).parent.parent
_RESULTS_DIR = _PROJECT_ROOT / "variance" / "results"

ALL_MODELS = ["bronze", "silver", "gold_naive", "gold"]

_MODEL_LABELS = {
    "bronze":     "Bronze (raw)",
    "silver":     "Silver (naive)",
    "gold_naive": "Naive Gold",
    "gold":       "Semantic Gold",
}

_MODEL_DESCRIPTION = {
    "bronze":     "Raw Bronze tables — fragmented schemas, no cross-source joins",
    "silver":     "SILVER.POSITIONS_INTEGRATED — naive union, A7–A11 embedded",
    "gold_naive": "GOLD_NAIVE.POSITIONS_NAIVE — assumption-based Gold, possibly worse",
    "gold":       "GOLD DW + semantic model — governed, correct answers",
}

_STATUS_EMOJI = {
    "CORRECT": "✅",
    "WRONG":   "❌",
    "NO_DATA": "⚪",
    "ERROR":   "⚠️",
}

_STATUS_COLOR = {
    "CORRECT": "#2ecc71",
    "WRONG":   "#e74c3c",
    "NO_DATA": "#f39c12",
    "ERROR":   "#95a5a6",
}

_STATUS_LABEL = {
    "CORRECT": "Correct",
    "WRONG":   "Wrong",
    "NO_DATA": "No data",
    "ERROR":   "Error",
}


@st.cache_data
def _cached_ground_truths() -> dict:
    return compute_all()


def _rescore(data: dict) -> dict:
    """Re-apply comparator scoring to raw rows in a results dict."""
    ground_truths = _cached_ground_truths()
    q_map = {q.id: q for q in QUESTIONS}

    for q_entry in data.get("questions", []):
        qid = q_entry["id"]
        q = q_map.get(qid)
        if q is None:
            continue
        gt = ground_truths[qid]
        for model in ALL_MODELS:
            mdata = q_entry.get(model)
            if mdata is None:
                continue
            if mdata.get("error"):
                mdata["status"] = "ERROR"
                mdata["variance"] = None
                mdata["value"] = None
            else:
                rows = mdata.get("rows") or []
                status, variance, value = score(rows, gt, q.result_type)
                mdata["status"] = status
                mdata["variance"] = variance
                mdata["value"] = value

    summary = data.setdefault("summary", {})
    questions = data.get("questions", [])
    total = len(questions)
    summary["total_questions"] = total
    for model in ALL_MODELS:
        statuses = [
            q.get(model, {}).get("status", "ERROR")
            for q in questions
            if q.get(model) is not None
        ]
        if statuses:
            correct = statuses.count("CORRECT")
            summary[f"{model}_correct"] = correct
            summary[f"{model}_accuracy_pct"] = round(correct / total * 100.0, 1)

    return data


def _badge(status: str | None) -> str:
    if not status:
        return "—"
    emoji = _STATUS_EMOJI.get(status, "?")
    label = _STATUS_LABEL.get(status, status)
    return f"{emoji} {label}"


def _fmt_value(value, result_type: str, ground_truth: float) -> str:
    if value is None:
        return "—"
    if result_type == "row_count":
        return f"{int(value):,} rows"
    if result_type == "percentage":
        return f"{value:.2f}%"
    if abs(ground_truth) >= 1_000:
        return f"${value:,.2f}"
    return f"{value:,.4f}"


def _fmt_gt(ground_truth: float, result_type: str) -> str:
    if result_type == "row_count":
        return f"{int(ground_truth):,} rows"
    if result_type == "percentage":
        return f"{ground_truth:.4f}%"
    return f"${ground_truth:,.2f}"


def _fmt_variance(variance, result_type: str, status: str) -> str:
    if variance is None or status in ("NO_DATA", "ERROR"):
        return "—"
    sign = "+" if variance > 0 else ""
    if result_type == "row_count":
        return f"{sign}{int(variance):,} rows"
    if result_type == "percentage":
        return f"{sign}{variance:.2f} pp"
    return f"{sign}{variance:.2f}%"


def _load_latest_results() -> dict | None:
    json_files = sorted(_RESULTS_DIR.glob("*.json"), reverse=True)
    if not json_files:
        return None
    return json.loads(json_files[0].read_text())


def _list_result_files() -> list[Path]:
    return sorted(_RESULTS_DIR.glob("*.json"), reverse=True)


# ── Page config ────────────────────────────────────────────────────────────────

st.set_page_config(
    page_title="GSF — Semantic Layer Demo",
    page_icon="💎",
    layout="wide",
)

st.title("💎 Gemstone Financial — Semantic Layer Demo")
st.caption(
    "Proving that a semantic layer is not optional convenience — it is a **governance mechanism** "
    "for AI-generated results.  Four tiers: Bronze → Silver → Naive Gold → Semantic Gold."
)

# ── Sidebar ────────────────────────────────────────────────────────────────────

with st.sidebar:
    st.header("Controls")

    st.subheader("Tiers to display")
    show_bronze     = st.checkbox("Bronze (raw)",   value=False)
    show_silver     = st.checkbox("Silver (naive)", value=True)
    show_gold_naive = st.checkbox("Naive Gold",     value=True)
    show_gold       = st.checkbox("Semantic Gold",  value=True)

    VISIBLE_MODELS = [
        m for m, show in [
            ("bronze",     show_bronze),
            ("silver",     show_silver),
            ("gold_naive", show_gold_naive),
            ("gold",       show_gold),
        ]
        if show
    ]

    st.divider()
    result_files = _list_result_files()
    if result_files:
        file_labels = [f.name for f in result_files]
        selected_label = st.selectbox("Results file", file_labels, index=0)
        selected_file = _RESULTS_DIR / selected_label
        data = _rescore(json.loads(selected_file.read_text()))
        st.caption(f"Run: {data.get('run_timestamp', '—')[:19].replace('T', ' ')} UTC")
    else:
        data = None

    st.divider()
    st.subheader("Re-run against Snowflake")
    run_model = st.selectbox(
        "Model(s)",
        ["all", "gold", "silver", "gold_naive", "bronze",
         "gold silver", "gold gold_naive"],
        index=0,
    )
    if st.button("▶ Run now", type="primary", use_container_width=True):
        cmd_models = run_model.split()
        cmd = [sys.executable, str(_PROJECT_ROOT / "variance" / "runner.py"),
               "--model"] + cmd_models
        with st.spinner("Running variance comparison… (2–4 minutes per model)"):
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                encoding="utf-8",
                errors="replace",
                cwd=str(_PROJECT_ROOT),
            )
        if result.returncode == 0:
            st.success("Done — reload the page to see results.")
            st.code(result.stdout[-2000:])
        else:
            st.error("Runner failed.")
            st.code(result.stderr[-2000:])

    st.divider()
    st.subheader("Upload results file")
    uploaded = st.file_uploader("Drop a results JSON here", type="json")
    if uploaded:
        data = _rescore(json.load(uploaded))

# ── No results guard ──────────────────────────────────────────────────────────

if not data:
    st.warning(
        "No results found in `variance/results/`. "
        "Run the comparison first:\n\n"
        "```bash\npython variance/runner.py\n```"
    )
    st.stop()

# ── Header scorecard ──────────────────────────────────────────────────────────

summary = data.get("summary", {})
questions = data.get("questions", [])
total = summary.get("total_questions", len(questions))
models_in_data = [m for m in ALL_MODELS if summary.get(f"{m}_correct") is not None]
visible_models = [m for m in VISIBLE_MODELS if m in models_in_data]

if not visible_models:
    st.info("Select at least one tier in the sidebar to display results.")
    st.stop()

scorecard_cols = st.columns(max(len(visible_models), 1))
for idx, model in enumerate(visible_models):
    correct = summary.get(f"{model}_correct")
    pct = summary.get(f"{model}_accuracy_pct")
    with scorecard_cols[idx]:
        label = _MODEL_LABELS[model]
        delta_color = "normal" if model == "gold" else "inverse"
        st.metric(
            label,
            f"{correct}/{total} correct",
            delta=f"{pct:.0f}% accuracy",
            delta_color=delta_color,
        )
        st.caption(_MODEL_DESCRIPTION[model])

st.divider()

# ── Summary bar chart ─────────────────────────────────────────────────────────

def _build_summary_chart(questions: list[dict], models: list[str]) -> go.Figure:
    status_order = ["CORRECT", "WRONG", "NO_DATA", "ERROR"]
    counts: dict[str, dict[str, int]] = {m: {s: 0 for s in status_order} for m in models}

    for q in questions:
        for m in models:
            mdata = q.get(m) or {}
            s = mdata.get("status", "ERROR")
            counts[m][s] = counts[m].get(s, 0) + 1

    fig = go.Figure()
    x_labels = [_MODEL_LABELS.get(m, m) for m in models]
    for status in status_order:
        y_vals = [counts[m][status] for m in models]
        if sum(y_vals) == 0:
            continue
        fig.add_trace(go.Bar(
            name=_STATUS_LABEL[status],
            x=x_labels,
            y=y_vals,
            marker_color=_STATUS_COLOR[status],
            text=y_vals,
            textposition="inside",
            insidetextanchor="middle",
        ))

    fig.update_layout(
        barmode="stack",
        title="Result status by tier",
        yaxis_title="Questions",
        yaxis=dict(tickmode="linear", dtick=1),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        height=340,
        margin=dict(l=0, r=0, t=50, b=0),
        plot_bgcolor="rgba(0,0,0,0)",
        paper_bgcolor="rgba(0,0,0,0)",
    )
    return fig


if visible_models:
    st.subheader("Result summary")
    st.plotly_chart(_build_summary_chart(questions, visible_models), use_container_width=True)
    st.divider()

# ── Comparison table ──────────────────────────────────────────────────────────

st.subheader("Question-by-question comparison")
st.caption("Expand a row to see the generated SQL, results, and failure narrative.")

for q in questions:
    qid = q["id"]
    codes = ", ".join(q["ambiguity_codes"])
    question_short = q["question"][:70] + ("…" if len(q["question"]) > 70 else "")
    gt = q["ground_truth"]
    result_type = q["result_type"]

    # Build compact status line for expander header
    status_parts = []
    for m in visible_models:
        mdata = q.get(m) or {}
        status = mdata.get("status", "ERROR")
        status_parts.append(f"{_MODEL_LABELS[m]}: {_badge(status)}")
    status_line = "  ·  ".join(status_parts)

    expander_label = f"**{qid}** [{codes}]  {question_short}   —   {status_line}"

    with st.expander(expander_label):
        st.markdown(
            f"**Ground truth:** {_fmt_gt(gt, result_type)}  "
            f"·  *{q['ground_truth_description']}*"
        )
        st.divider()

        n_cols = len(visible_models)
        cols = st.columns(n_cols) if n_cols > 0 else []

        for idx, model in enumerate(visible_models):
            mdata = q.get(model) or {}
            status = mdata.get("status", "ERROR")
            value = mdata.get("value")
            variance = mdata.get("variance")
            sql = mdata.get("sql") or ""
            rows = mdata.get("rows") or []
            error = mdata.get("error")

            with cols[idx]:
                st.markdown(f"#### {_MODEL_LABELS[model]}")
                st.markdown(
                    f"**Status:** {_badge(status)}  "
                    f"**Value:** {_fmt_value(value, result_type, gt)}  "
                    f"**Δ:** {_fmt_variance(variance, result_type, status)}"
                )

                if error:
                    st.error(f"Error: {error}")

                if sql:
                    st.markdown("**Generated SQL:**")
                    st.code(sql, language="sql")

                if rows:
                    st.markdown(f"**Result** ({len(rows)} rows):")
                    st.dataframe(
                        pd.DataFrame(rows[:10]),
                        use_container_width=True,
                        hide_index=True,
                    )
                    if len(rows) > 10:
                        st.caption(f"… {len(rows) - 10} more rows not shown")
                elif not error:
                    st.info("No rows returned.")

        if q.get("failure_mode_silver"):
            st.divider()
            st.markdown("**Why ungoverned layers fail here:**")
            st.info(q["failure_mode_silver"])

st.divider()
st.caption(
    f"Run ID: {data.get('run_id', '—')}  ·  "
    f"Timestamp: {data.get('run_timestamp', '—')[:19].replace('T', ' ')} UTC  ·  "
    "Ground truth computed from `data/seed_v2/` (independent of Snowflake)"
)
