"""
Gemstone Financial — Semantic Layer Bias Demo
=============================================
Streamlit visualization for the Silver vs Gold Cortex Analyst variance study.

Loads the most recent run from variance/results/*.json and renders:
  1. Header scorecard  — Gold vs Silver accuracy at a glance
  2. Summary bar chart — Status breakdown by question
  3. Comparison table  — One row per question with colored status badges
  4. Detail expanders  — Full SQL, result rows, ground truth, and failure narrative

Requires a results file generated by:
  python variance/runner.py

Run with:
  streamlit run app/streamlit_app.py
"""

import json
import subprocess
import sys
from pathlib import Path

import pandas as pd
import plotly.graph_objects as go
import streamlit as st

sys.path.insert(0, str(Path(__file__).parent.parent))
from variance.comparator import score
from variance.ground_truth import compute_all
from variance.questions import QUESTIONS

_PROJECT_ROOT = Path(__file__).parent.parent
_RESULTS_DIR = _PROJECT_ROOT / "variance" / "results"


@st.cache_data
def _cached_ground_truths() -> dict:
    return compute_all()


def _rescore(data: dict) -> dict:
    """Re-apply comparator scoring to raw rows in a results dict.

    The runner saves scored results, but comparator logic can be updated
    without re-running Cortex. This re-scores from the stored raw rows
    so the UI always reflects the current comparator.
    """
    ground_truths = _cached_ground_truths()
    q_map = {q.id: q for q in QUESTIONS}

    for q_entry in data.get("questions", []):
        qid = q_entry["id"]
        q = q_map.get(qid)
        if q is None:
            continue
        gt = ground_truths[qid]
        for model in ("gold", "silver"):
            mdata = q_entry.get(model)
            if mdata is None:
                continue
            if mdata.get("error"):
                mdata["status"] = "ERROR"
                mdata["variance"] = None
                mdata["value"] = None
            else:
                rows = mdata.get("rows") or []
                status, variance, value = score(rows, gt, q.result_type)
                mdata["status"] = status
                mdata["variance"] = variance
                mdata["value"] = value

    # Recompute summary
    summary = data.setdefault("summary", {})
    questions = data.get("questions", [])
    total = len(questions)
    summary["total_questions"] = total
    for model in ("gold", "silver"):
        statuses = [
            q.get(model, {}).get("status", "ERROR")
            for q in questions
            if q.get(model) is not None
        ]
        if statuses:
            correct = statuses.count("CORRECT")
            summary[f"{model}_correct"] = correct
            summary[f"{model}_accuracy_pct"] = round(correct / total * 100.0, 1)

    return data

# ── Status display helpers ─────────────────────────────────────────────────────

_STATUS_EMOJI = {
    "CORRECT": "✅",
    "WRONG": "❌",
    "NO_DATA": "⚪",
    "ERROR": "⚠️",
}

_STATUS_COLOR = {
    "CORRECT": "#2ecc71",
    "WRONG": "#e74c3c",
    "NO_DATA": "#f39c12",
    "ERROR": "#95a5a6",
}

_STATUS_LABEL = {
    "CORRECT": "Correct",
    "WRONG": "Wrong",
    "NO_DATA": "No data",
    "ERROR": "Error",
}

_MODEL_LABELS = {
    "gold": "Gold (governed)",
    "silver": "Silver (naive)",
}


def _badge(status: str | None) -> str:
    if not status:
        return "—"
    emoji = _STATUS_EMOJI.get(status, "?")
    label = _STATUS_LABEL.get(status, status)
    return f"{emoji} {label}"


def _fmt_value(value, result_type: str, ground_truth: float) -> str:
    if value is None:
        return "—"
    if result_type == "row_count":
        return f"{int(value):,} rows"
    if result_type == "percentage":
        return f"{value:.2f}%"
    # scalar — format as currency if large, otherwise plain number
    if abs(ground_truth) >= 1_000:
        return f"${value:,.2f}"
    return f"{value:,.4f}"


def _fmt_gt(ground_truth: float, result_type: str) -> str:
    if result_type == "row_count":
        return f"{int(ground_truth):,} rows"
    if result_type == "percentage":
        return f"{ground_truth:.4f}%"
    return f"${ground_truth:,.2f}"


def _fmt_variance(variance, result_type: str, status: str) -> str:
    if variance is None or status in ("NO_DATA", "ERROR"):
        return "—"
    sign = "+" if variance > 0 else ""
    if result_type == "row_count":
        return f"{sign}{int(variance):,} rows"
    if result_type == "percentage":
        return f"{sign}{variance:.2f} pp"
    return f"{sign}{variance:.2f}%"


# ── Data loading ───────────────────────────────────────────────────────────────

def _load_latest_results() -> dict | None:
    json_files = sorted(_RESULTS_DIR.glob("*.json"), reverse=True)
    if not json_files:
        return None
    return json.loads(json_files[0].read_text())


def _list_result_files() -> list[Path]:
    return sorted(_RESULTS_DIR.glob("*.json"), reverse=True)


# ── Page layout ────────────────────────────────────────────────────────────────

st.set_page_config(
    page_title="GSF — Semantic Layer Bias Demo",
    page_icon="💎",
    layout="wide",
)

st.title("💎 Gemstone Financial — Semantic Layer Bias Demo")
st.caption(
    "Proving that a semantic layer is not optional convenience — it is a **bias control mechanism** "
    "for AI-generated results."
)

# ── Sidebar ────────────────────────────────────────────────────────────────────

with st.sidebar:
    st.header("Controls")

    result_files = _list_result_files()
    if result_files:
        file_labels = [f.name for f in result_files]
        selected_label = st.selectbox("Results file", file_labels, index=0)
        selected_file = _RESULTS_DIR / selected_label
        data = _rescore(json.loads(selected_file.read_text()))
        st.caption(f"Run: {data.get('run_timestamp', '—')[:19].replace('T', ' ')} UTC")
    else:
        data = None

    st.divider()
    st.subheader("Re-run against Snowflake")
    run_model = st.radio("Model", ["both", "gold", "silver"], horizontal=True)
    if st.button("▶ Run now", type="primary", use_container_width=True):
        with st.spinner("Running variance comparison… (this takes 2–4 minutes)"):
            result = subprocess.run(
                [sys.executable, str(_PROJECT_ROOT / "variance" / "runner.py"),
                 "--model", run_model],
                capture_output=True,
                text=True,
                encoding="utf-8",
                errors="replace",
                cwd=str(_PROJECT_ROOT),
            )
        if result.returncode == 0:
            st.success("Done — reload the page to see results.")
            st.code(result.stdout[-2000:])
        else:
            st.error("Runner failed.")
            st.code(result.stderr[-2000:])

    st.divider()
    st.subheader("Upload results file")
    uploaded = st.file_uploader("Drop a results JSON here", type="json")
    if uploaded:
        data = _rescore(json.load(uploaded))

# ── No results guard ──────────────────────────────────────────────────────────

if not data:
    st.warning(
        "No results found in `variance/results/`. "
        "Run the comparison first:\n\n"
        "```bash\npython variance/runner.py\n```"
    )
    st.stop()

# ── Header scorecard ──────────────────────────────────────────────────────────

summary = data.get("summary", {})
questions = data.get("questions", [])
total = summary.get("total_questions", len(questions))

gold_correct = summary.get("gold_correct")
silver_correct = summary.get("silver_correct")
gold_pct = summary.get("gold_accuracy_pct")
silver_pct = summary.get("silver_accuracy_pct")
diverge = summary.get("questions_diverge")

col1, col2, col3, col4 = st.columns(4)

with col1:
    if gold_correct is not None:
        st.metric("Gold (governed)", f"{gold_correct}/{total} correct",
                  delta=f"{gold_pct:.0f}% accuracy", delta_color="normal")
    else:
        st.metric("Gold (governed)", "not run")

with col2:
    if silver_correct is not None:
        delta_val = f"{silver_pct:.0f}% accuracy"
        st.metric("Silver (naive)", f"{silver_correct}/{total} correct",
                  delta=delta_val, delta_color="inverse")
    else:
        st.metric("Silver (naive)", "not run")

with col3:
    if diverge is not None:
        st.metric("Questions diverge", f"{diverge} of {total}")

with col4:
    if gold_correct is not None and silver_correct is not None:
        lift = gold_correct - silver_correct
        st.metric("Correct answer lift", f"+{lift} questions",
                  delta="semantic layer advantage", delta_color="normal")

st.divider()

# ── Summary bar chart ─────────────────────────────────────────────────────────

def _build_summary_chart(questions: list[dict]) -> go.Figure:
    models_in_data = [m for m in ("gold", "silver") if questions[0].get(m) is not None]
    status_order = ["CORRECT", "WRONG", "NO_DATA", "ERROR"]

    counts: dict[str, dict[str, int]] = {m: {s: 0 for s in status_order} for m in models_in_data}
    for q in questions:
        for m in models_in_data:
            mdata = q.get(m) or {}
            s = mdata.get("status", "ERROR")
            counts[m][s] = counts[m].get(s, 0) + 1

    fig = go.Figure()
    x_labels = [_MODEL_LABELS.get(m, m) for m in models_in_data]
    for status in status_order:
        y_vals = [counts[m][status] for m in models_in_data]
        if sum(y_vals) == 0:
            continue
        fig.add_trace(go.Bar(
            name=_STATUS_LABEL[status],
            x=x_labels,
            y=y_vals,
            marker_color=_STATUS_COLOR[status],
            text=y_vals,
            textposition="inside",
            insidetextanchor="middle",
        ))

    fig.update_layout(
        barmode="stack",
        title="Result status by model",
        yaxis_title="Questions",
        yaxis=dict(tickmode="linear", dtick=1),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        height=320,
        margin=dict(l=0, r=0, t=50, b=0),
        plot_bgcolor="rgba(0,0,0,0)",
        paper_bgcolor="rgba(0,0,0,0)",
    )
    return fig


st.subheader("Result summary")
st.plotly_chart(_build_summary_chart(questions), use_container_width=True)

st.divider()

# ── Comparison table ──────────────────────────────────────────────────────────

st.subheader("Question-by-question comparison")
st.caption("Expand a row to see the generated SQL, results, and failure narrative.")

models_available = [m for m in ("gold", "silver") if questions[0].get(m) is not None]

for q in questions:
    qid = q["id"]
    codes = ", ".join(q["ambiguity_codes"])
    question_short = q["question"][:70] + ("…" if len(q["question"]) > 70 else "")
    gt = q["ground_truth"]
    result_type = q["result_type"]

    # Build status summary line for the expander header
    status_parts = []
    for m in models_available:
        mdata = q.get(m) or {}
        status = mdata.get("status", "ERROR")
        status_parts.append(f"{m.capitalize()}: {_badge(status)}")
    status_line = "  ·  ".join(status_parts)

    expander_label = f"**{qid}** [{codes}]  {question_short}   —   {status_line}"

    with st.expander(expander_label):
        # Ground truth row
        st.markdown(
            f"**Ground truth:** {_fmt_gt(gt, result_type)}  "
            f"·  *{q['ground_truth_description']}*"
        )
        st.divider()

        cols = st.columns(len(models_available))
        for idx, model in enumerate(models_available):
            mdata = q.get(model) or {}
            status = mdata.get("status", "ERROR")
            value = mdata.get("value")
            variance = mdata.get("variance")
            sql = mdata.get("sql") or ""
            rows = mdata.get("rows") or []
            error = mdata.get("error")

            with cols[idx]:
                label = "Gold — governed" if model == "gold" else "Silver — naive"
                st.markdown(f"#### {label}")
                st.markdown(
                    f"**Status:** {_badge(status)}  "
                    f"**Value:** {_fmt_value(value, result_type, gt)}  "
                    f"**Δ:** {_fmt_variance(variance, result_type, status)}"
                )

                if error:
                    st.error(f"Error: {error}")

                if sql:
                    st.markdown("**Generated SQL:**")
                    st.code(sql, language="sql")

                if rows:
                    st.markdown(f"**Result** ({len(rows)} rows):")
                    display_rows = rows[:10]
                    st.dataframe(
                        pd.DataFrame(display_rows),
                        use_container_width=True,
                        hide_index=True,
                    )
                    if len(rows) > 10:
                        st.caption(f"… {len(rows) - 10} more rows not shown")
                elif not error:
                    st.info("No rows returned.")

        # Failure narrative (always shown)
        if q.get("failure_mode_silver"):
            st.divider()
            st.markdown("**Why Silver fails here:**")
            st.info(q["failure_mode_silver"])

st.divider()
st.caption(
    f"Run ID: {data.get('run_id', '—')}  ·  "
    f"Timestamp: {data.get('run_timestamp', '—')[:19].replace('T', ' ')} UTC  ·  "
    "Ground truth computed from `data/seed_v2/` (independent of Snowflake)"
)
